apiVersion: v1
kind: Service
metadata:
  name: tweets-server
  namespace: pplevins-dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30010
  selector:
    app: tweets-server